media:
  input: public/uploads
  output: /uploads

content:
  - name: news
    label: Nyheter
    type: collection
    path: src/content/news
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{fields.title}.md"

    view:
      fields: [title, date, categories]

    fields:
      - name: title
        label: Tittel
        type: string
        required: true

      - name: date
        label: Publisert dato
        type: date
        default: now
        required: true

      - name: ingress
        label: Kort ingress
        type: text
        description: Kort oppsummering av artikkelen (vises i nyhetslisten)

      - name: cover
        label: Hovedbilde
        type: image

      - name: categories
        label: Kategorier
        type: select
        options:
          multiple: true
          values:
            - value: aarsmote
              label: Årsmøte
            - value: arrangementer
              label: Arrangementer
            - value: kurstrening
              label: Kurs og trening
            - value: styret
              label: Styret
            - value: turneringer
              label: Turneringer
            - value: ukategorisert
              label: Ukategorisert

      - name: attachments
        label: Dokumenter (PDF)
        type: file
        options:
          multiple:
            max: 10
          extensions: [pdf]

      - name: draft
        label: Lagre som utkast
        type: boolean
        default: false

      - name: body
        label: Artikkel
        type: rich-text
        options:
          media: false
          switcher: false
